### ISSUE TITLE
About the kernel simulation

### ISSUE THREAD

**Issue by dawnlh** [dongjxjx/dwdn#5]
Hi~ @dongjxjx ,
Thanks for your wonderful work. It seems that the code you provided didn't contain training data simulation part. I find that the blur kernel generation has a great influence on the performance, and I cannot reproduce your results with my training data. So could you please share your data simulation code? Thanks a lot!

**Comment by hungnguyen311299** [comment]
Despite my best efforts at following details in the paper (the training script was missing), I was unable to reproduce the results too.
